name: Vercel production deploy

env:
    VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
    VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
    push:
        branches:
            - main

jobs:
    Deploy-Production:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Install Vercel CLI
              run: npm i -g vercel

            - name: Pull Vercel Environment
              run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

            - name: Build Project
              run: vercel build --prod  --token=${{ secrets.VERCEL_TOKEN }}

            - name: Deploy Project
              run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
